### ISSUE TITLE
Do not use global environment to install Pluto

### ISSUE THREAD

**Issue by giordano** [UCL-ARC/ood-pluto#1]
First of all, I played a little bit with this app today and it's working great for me, thanks!

The only suggestion I have is not to install Pluto in the global environment, and instead use a separate [shared environment](https://pkgdocs.julialang.org/v1/environments/#Shared-environments), like `@ood-pluto-julia-1.10` (better to index by julia minor version, to avoid issues when switching between different versions), to keep things tidy and don't mess with the user's main environment.  This can be achieved by either exporting the environment variable [`JULIA_PROJECT`](https://docs.julialang.org/en/v1/manual/environment-variables/#JULIA_PROJECT), or passing the argument [`--project=`](https://pkgdocs.julialang.org/v1/environments/#Using-someone-else's-project).

**Comment by ikirker** [comment]
So I guess I could do something like:

```bash
julia_version="$(julia --version | cut -f 3 -d ' ' | cut -f -2 -d '.')"
```

before running the instance of Julia I'm going to use for the actual Pluto instance.

I didn't see e.g. a version pseudovariable you could use in the `--project` option.

I saw that I could also do something like:

```julia
Pkg.activate(string("ood-pluto-env-", VERSION.major, ".", VERSION.minor); shared=true)
```

from within the script, which might be better?

**Comment by giordano** [comment]
> I saw that I could also do something like:
> 
> ```julia
> Pkg.activate(string("ood-pluto-env-", VERSION.major, ".", VERSION.minor); shared=true)
> ```
> 
> from within the script, which might be better?

Yes, that looks great!

**Comment by ikirker** [comment]
Added, deployed as 1.1.0.
